### ISSUE TITLE
/devices endpoint changing

### ISSUE THREAD

**Issue by deanlyoung** [netmanchris/pyawair#25]
http://developer-apis.awair.is/v1/users/self/devices

will become

http://developer-apis.awair.is/v1/devices

**Comment by netmanchris** [comment]
Hey @deanlyoung  it possible to leave both endpoints in place while we make the transition in the library?

What’s the timing here? Just planning the work :)

**Comment by deanlyoung** [comment]
Moving kind of quick on this change because it has to go out with some more urgent changes (additions) to org > device list (which is currently missing separated `deviceType` and `deviceId` key/value pairs. Plus, this endpoint here was missing `uuid`. Not sure we’ll be able to keep both alive 😬

My gut was telling me this endpoint isn’t _that_ critical, unless someone is pulling devices programmatically to them pull all available air data points from all available devices. Is that how you’ve set it up?

Sorry about this breaking change. Big oversight on my part, and we should have caught it earlier. It really belongs in the Device section instead of Users...

**Comment by danielsjf** [comment]
@deanlyoung actually it is quite a fundamental one as we use it to translate the name to an ID and type.

I don't completely get your comment, but I hope querying the devices will not add ID and type info as we don't necessarily have that at that point.

If this is not the case, we need a new endpoint to get the ID and type from the device name. Alternatively, each endpoint should also work with just a name instead of ID and type.

**Comment by deanlyoung** [comment]
@danielsjf @netmanchris thanks for the feedback! I talked with the team and we will support both endpoints, but only the new ones will appear in the documentation. I'll try to preserve (archive) the old docs for reference.

**Comment by netmanchris** [comment]
@deanlyoung. That sounds great!  I was thinking this should be easy enough to just change the API version for these endpoints from 1 to 2.  This gives us time to implement the new APIs and ensure we don’t break anything in the process. 

Really appreciate you guys working with us so that we can get this right!  Once you get the new API docs loaded, let us know so that we can start the work of implementing the new APIs and make sure that the output is consistent with the current codebase.

**Comment by deanlyoung** [comment]
@netmanchris actually, ended up not having make any changes to Get endpoints, but definitely restructured the docs to make them more intuitive. If everything goes smoothly, it should go live tonight.

The Put/Post endpoints / behavior definitely will change with the update though. Turns out the initial implementation was updating deprecated data on the backend (i.e. not doing anything), but I believe no one has been using those endpoints yet. The beauty of Beta!
